language: node_js
node_js:
  - "8"
sudo: required
dist: trusty
addons:
  chrome: stable
before_install:
  - sudo apt-get update
# disable applitools pending upgrade to rhtmlBuildUtils 5.0.0 and port to jest test suite
script:
  - true
