name: Build rhtmlMoonPlot

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build rhtmlMoonPlot
    permissions:
      checks: write
      contents: read
    uses: Displayr/nixr-public/.github/workflows/build-flake-installable.yaml@master
    with:
      installable-path: pkgs.x86_64-linux.rPackages.rhtmlMoonPlot
      build-args: --override-input rhtmlMoonPlot .
      installable-name: rhtmlMoonPlot
    secrets: inherit
